# Generated by Django 5.0.3 on 2024-03-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desciption',
            new_name='description',
        ),
    ]
