# Generated by Django 5.0.3 on 2024-03-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_desciption_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catrgory',
            new_name='category',
        ),
    ]
