# Generated by Django 5.0.3 on 2024-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_is_sold_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
