# Generated by Django 5.0.3 on 2024-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_marketplace_itemmarketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmarketplace',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
