# Generated by Django 5.0.3 on 2024-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_itemmarketplace_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='api_url',
            field=models.URLField(default='http://127.0.0.1:8080/api/products/'),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='token',
            field=models.CharField(default='sda', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8080'),
        ),
    ]
