# Generated by Django 5.0.3 on 2024-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_marketplace_api_url_marketplace_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
